// vue-2/src/page/DataFetch.vue
<script>
export default {
  data() {
    return {
      data: null,
      loading: false,
    }
  },
  async mounted() {
    this.loading = true;
    const url = "https://pokeapi.co/api/v2/pokemon/ditto";
    const response = await fetch(url).then((res) => {
      this.loading = false;
      return res.json();
    })
    this.data = response;
  }
}
</script>

<template>
  <div>
    <div>DataFetch</div>
    <div v-if="loading">Loading...</div>
    <div v-else>
      <img :src="data.sprites.front_default" />
      <div>{{ data.species.name }}</div>
    </div>
</div>
</template>

// react/src/pages/DataFetch.tsx
import React, { useState, useEffect } from 'react';

interface PokeAPI {
  sprites: {
    front_default: string;
  };
  species: {
    name: string;
  };
}

const DataFetch: React.FC = () => {
  const [data, setData] = useState<PokeAPI | null>(null);
  const url = "https://pokeapi.co/api/v2/pokemon/ditto";

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch(url);
        const json = await response.json();
        setData(json);
      } catch (error) {
        console.error(error);
      }
    };

    fetchData();
  }, []);

  return (
    <div>
      <h1>Data Fetch</h1>
      {data && (
        <div>
          <p>{data.species.name}</p>
          <img src={data.sprites.front_default} alt={data.species.name} />
        </div>
      )}
    </div>
  );
};

export default DataFetch;
