// vue-2/src/page/Todo.vue
<script>
export default {
  data() {
    return {
      title: "",
      todos: [{
        id: 1,
        title: "タスク1",
        completed: false
      }]
    }
  },
  methods: {
    updateTitle(value) {
      this.title = value;
    },
    addTodo() {
      this.todos.push({
        id: this.todos.length + 1,
        title: this.title,
        completed: false
      });
      this.title = "";
    },
    completedTodo(id) {
      const todo = this.todos.find(todo => todo.id === id);
      if (todo) {
        todo.completed = !todo.completed;
      }
    }
  }
}
</script>

<template>
  <div>
    <h1>Todo</h1>
    <v-text-field
      :value="title"
      @input="updateTitle"
      label="タスクを入力"
      placeholder="新しいタスクを追加..."
      outlined
      clearable
    ></v-text-field>
    <v-btn @click="addTodo">追加</v-btn>
    <ul class="list">
      <li v-for="todo in todos.filter(todo => !todo.completed)" :key="todo.id" class="list-item">
        <p class="p">{{ todo.title }}</p>
        <input type="checkbox" :checked="todo.completed" @change="() => completedTodo(todo.id)">
      </li>
    </ul>
  </div>
</template>

<style>
.list {
  list-style: none;
  padding-left: 0 !important;
  margin-top: 20px;
}

.list-item {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 4px;
}

.p {
  margin-bottom: 0 !important;
}
</style>

// react/src/pages/Todo.tsx
import React, { useState } from 'react';
import Button from '@/components/Button';

interface TodoItem {
  id: number;
  title: string;
  completed: boolean;
}

const Todo: React.FC = () => {
  const [title, setTitle] = useState('');
  const [todos, setTodos] = useState<TodoItem[]>([
    { id: 1, title: 'Todo 1', completed: false },
    { id: 2, title: 'Todo 2', completed: false },
    { id: 3, title: 'Todo 3', completed: false },
  ]);

  const updateTitle = (event: React.ChangeEvent<HTMLInputElement>) => {
    setTitle(event.target.value);
  };

  const addTodo = () => {
    setTodos([
      ...todos,
      {
        id: todos.length + 1,
        title: title,
        completed: false,
      },
    ]);
    setTitle('');
  };

  const completedTodo = (id: number) => {
    setTodos(todos.map(todo => 
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    ));
  };

  return (
    <div>
      <h1>Todo Page</h1>
      <div>
        <input value={title} onChange={updateTitle} />
        <Button onClick={addTodo}>追加</Button>
      </div>
      <ul>
        {todos
          .filter(todo => !todo.completed)
          .map((item) => (
            <li key={item.id}>
              <div className="item">
                {item.title}
                <input
                  type="checkbox"
                  checked={item.completed}
                  onChange={() => completedTodo(item.id)}
                />
              </div>
            </li>
          ))}
      </ul>
    </div>
  );
};

export default Todo;
