// react/src/pages/Counter.tsx
import React, { useState } from 'react';
import Button from '@/components/Button';

const Counter: React.FC = () => {
  const [count, setCount] = useState(0);

  const increment = () => {
    setCount(count + 1);
  };

  const decrement = () => {
    setCount(count - 1);
  };

  return (
    <div>
      <h1>Counter Page</h1>
      <p>{count}</p>
      <Button onClick={increment}>Increment</Button>
      <Button onClick={decrement}>Decrement</Button>
    </div>
  );
};

export default Counter;

// src/page/Counter.vue
<script setup lang="ts">
import { ref } from 'vue';
import Button from '@/components/button.vue'

// 状態の宣言
const count = ref(0)

const increment = () => {
  count.value++
}
const decrement = () => {
  count.value--
}
</script>

<template>
  <h1>Counter Page</h1>
  <p>{{ count }}</p>
  <Button :onClick="increment" label="Increment" />
  <Button :onClick="decrement" label="Decrement" />
</template>
