// react/src/pages/Home.tsx
import React from 'react';
import { Link } from 'react-router-dom';

const Home: React.FC = () => {
  const list = [
    { name: 'Counter', path: '/counter' },
    { name: 'Todo', path: '/todo' },
    { name: 'Data Fetch', path: '/data-fetch' },
  ];

  return (
    <div>
      <h1>Home Page</h1>
      <ul className="list">
        {list.map((item) => (
          <li key={item.name} className="list-item">
            <Link to={item.path}>{item.name}</Link>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Home;

// src/page/Home.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'

const list = [
  { name: 'Counter', path: '/counter' },
  { name: 'Todo', path: '/todo' },
]
</script>

<template>
  <h1>Home Page</h1>
  <ul class="list">
    <li v-for="item in list" class="list-item">
      <RouterLink :to="item.path">
        {{ item.name }}
      </RouterLink>
    </li>
  </ul>
</template>

<style scoped>
.list {
  padding: 0;
}

.list-item {
  list-style: none;
}
</style>
